repos:
  - repo: https://github.com/kynan/nbstripout
    rev: 0.8.1
    hooks:
      - id: nbstripout
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v5.0.0 # Use the ref you want to point at
    hooks:
      - id: check-added-large-files
        args: ["--maxkb=2048"]
  - repo: https://github.com/astral-sh/ruff-pre-commit
    # Ruff version.
    rev: v0.15.0
    hooks:
      # Run the linter.
      - id: ruff
        types_or: [python, pyi] # Don't run on `jupyter` files
        args: [--fix]
      # Run the formatter.
      - id: ruff-format
        types_or: [python, pyi] # Don't run on `jupyter` files
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v3.2.0
    hooks:
      - id: trailing-whitespace
  - repo: local
    hooks:
      - id: pnpm-run-lint
        name: pnpm run lint
        language: system
        entry: bash -c 'cd frontend && pnpm run lint --max-warnings 0'
        files: ^frontend/src/.*$
        pass_filenames: false
        stages: [pre-commit]
      - id: pnpm-run-build
        name: pnpm run build
        language: system
        entry: bash -c 'cd frontend && pnpm run build'
        files: ^frontend/src/.*$
        pass_filenames: false
        stages: [pre-push]
      - id: pyright
        name: Pyright type-checking
        language: system
        entry: bash -c 'uv run pyright'
        files: ^unmute/.*$
        pass_filenames: false
        stages: [pre-commit]
